blueprint:
  name: Christmas Tree RF Controller (Mode + Brightness + Reset)
  description: >
    Controls a Christmas tree RF controller via 3 button entities:
    Mode cycles through modes; Light-/Light+ adjust brightness 0..12.
    Uses helpers to track internal state and supports a Reset that forces
    mode to Off and brightness to 0 on the next brightness change before setting target.
  domain: automation

  input:
    rf_mode_button:
      name: RF Mode button
      description: An ESPHome button entity that cycles the Christmas tree mode.
      default: button.tree_rf_bridge_tree_mode
      selector:
        entity:
          domain: button

    rf_light_minus_button:
      name: RF Light- button
      description: An ESPHome button entity that decreases the Christmas tree brightness.
      default: button.tree_rf_bridge_tree_light_minus
      selector:
        entity:
          domain: button

    rf_light_plus_button:
      name: RF Light+ button
      description: An ESPHome button entity that increases the Christmas tree brightness.
      default: button.tree_rf_bridge_tree_light_plus
      selector:
        entity:
          domain: button

    desired_mode:
      name: Desired mode
      description: Helper to select the desired Christmas tree mode. This must be an input_select.
      default: input_select.christmas_tree_mode
      selector:
        entity:
          domain: input_select

    desired_brightness:
      name: Desired brightness
      description: Helper to select the desired Christmas tree brightness (min 0, max 12, step 1).
      default: input_number.christmas_tree_brightness
      selector:
        entity:
          domain: input_number

    reset_button:
      name: Reset button
      description: >
        Helper to set the state of the Christmas tree to Mode=Off and calibrate the brightness
        on the next brightness change.
      default: input_button.christmas_tree_reset
      selector:
        entity:
          domain: input_button

    state_command_delay:
      name: Command delay
      description: Delay in ms between button presses to allow RF controller to process the button.
      default: 1000
      selector:
        number:
          unit_of_measurement: "ms"
          min: 100
          max: 2000
          step: 50
      
    idle_time_delay:
      name: Idle time delay
      description: Minimum time in seconds that desired_mode or desired_brightness must be stable before acting.
      default: 5
      selector:
        number:
          unit_of_measurement: "s"
          min: 1
          max: 60
          step: 1

    internal_state:
      name: Internal state of the tree
      description: >
        State of the tree. This is an input_number with range (0..256) that tracks the current brightness
        (0..12) and mode (0..5) as brightness + mode*16. If brightness is 15, a reset is pending.
      default: input_number.christmas_tree_state
      selector:
        entity:
          domain: input_number
    
mode: queued
max: 10

trigger:
  - platform: state
    entity_id: !input desired_mode
    for: !input idle_time_delay
    id: mode_change
  - platform: state
    entity_id: !input desired_brightness
    for: !input idle_time_delay
    id: brightness_change
  - platform: state
    entity_id: !input reset_button
    id: reset_press

variables:
    internal_state_ent: !input internal_state
    internal_state_val: "{{ states(internal_state_ent) | int(0) }}"
    current_mode: "{{ (internal_state_val | abs // 16) | int }}"
    current_brightness: "{{ (internal_state_val | abs % 16) | int }}"
    reset_pending: "{{ current_brightness == 15 }}"
    rplus_ent: !input rf_light_plus_button
    rminus_ent: !input rf_light_minus_button

action:
  - choose:
      # --- RESET ---
      - conditions: "{{ trigger.id == 'reset_press' }}"
        sequence:
          # Mark as "unknown brightness; assume Off" (per your contract).
          - service: input_number.set_value
            target:
              entity_id: "{{ internal_state_ent }}"
            data:
              # This sets the mode to zero and brightness to 15 (reset pending)
              value: 15
          
      # --- MODE CHANGED ---
      - conditions: "{{ trigger.id == 'mode_change' }}"
        sequence:
          # Steps forward through the ring: (target - current) mod 6
          - variables:
              desired_mode_index: >
                {% set st = states(trigger.entity_id) %}
                {% set options = state_attr(trigger.entity_id, 'options') %}
                {{ options.index(st) if st in options else 0  }}
              steps: >
                {{ (desired_mode_index - current_mode) % 6 }}
          - repeat:
              count: "{{ steps | int(0) }}"
              sequence:
                - service: button.press
                  target:
                    entity_id: !input rf_mode_button
                - delay:
                    milliseconds: !input state_command_delay
          - service: input_number.set_value
            target:
              entity_id: !input internal_state
            data:
              value: "{{ desired_mode_index * 16 + current_brightness }}"

      # --- BRIGHTNESS CHANGED ---
      - conditions: "{{ trigger.id == 'brightness_change' }}"
        sequence:

          # If reset_pending, force brightness down to 0 or up to 12 first
          # then proceed to set the desired level.
          - if: "{{ reset_pending }}"
            then:
              - variables:
                  target_b: "{{ desired_brightness | int(0) }}"
                  go_to_high: "{{ target_b > 6 }}"
                  reset_button_entity: "{{ iif(go_to_high, rplus_ent, rminus_ent) }}"
                  # Set this speculatively. This will override the pending reset state.
                  current_brightness: "{{ iif(go_to_high, 12, 0) }}"

              # Force to an endpoint (0 or 12)
              - repeat:
                  count: 12
                  sequence:
                    - service: button.press
                      target:
                        entity_id: "{{ reset_button_entity }}"
                    - delay:
                        milliseconds: !input state_command_delay
          - variables:
              desired_brightness: "{{ states(trigger.entity_id) | int(0) }}"
              # This selects the correct button based on desired vs current brightness
              button_entity: "{{ iif(desired_brightness > current_brightness, rplus_ent, rminus_ent) }}"
              # How many presses are needed
              press_count: "{{ (desired_brightness - current_brightness) | abs }}"
          - repeat:
              count: "{{ press_count }}"
              sequence:
                - service: button.press
                  target:
                    entity_id: "{{ button_entity }}"
                - delay:
                    milliseconds: !input state_command_delay

          # Update internal state to reflect new mode + brightness, clearing any reset pending.
          - service: input_number.set_value
            target:
              entity_id: !input internal_state
            data:
              value: "{{ desired_brightness + current_mode * 16 }}"
