blueprint:
  name: Control a light from multiple presense sensors
  description: >
    TBD
  domain: automation

  input:
    people_sensors:
      name: Motion / presence sensors
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - motion
            - occupancy
            - presence
          multiple: true
    switch_entity:
      name: Switch to control
      selector:
        target:
          entity:
            domain: 
              - switch
    no_motion_for:
      name: No-motion duration (minutes)
      selector:
        duration:
      default:
        hours: 0
        minutes: 1
        seconds: 0

variables:
  sensors: !input people_sensors

triggers:
  - trigger: state
    entity_id: !input people_sensors
    to: "on"
    id: on_trigger
  - trigger: state
    entity_id: !input people_sensors
    to: "off"
    for: !input no_motion_for
    id: off_trigger

action:
  - choose:
      # Turn on immediately
      - conditions:
          - condition: trigger
            id: on_trigger
        sequence:
          - service: switch.turn_on
            target: !input switch_entity
      # Turn off only if all sensors are off
      - conditions:
          - condition: trigger
            id: off_trigger
          - condition: template
            value_template: >
              {{ expand(sensors) | selectattr('state', 'eq', 'on') | list | count == 0 }}
        sequence:
          - service: switch.turn_off
            target: !input switch_entity

