blueprint:
  name: Control door lock
  description: >
    Control the front door lock
  domain: automation
  input:
    door_lock:
      name: Door Lock
      description: >
        Lock entity for the door.
      selector:
        entity:
          domain: lock
    door_open_sensor:
      name: Door Sensor
      description: >
        Binary sensor that detects whether the front door is open or closed. It is a binary sensor that is 'on' when the door is closed.
      selector:
        entity:
          domain: binary_sensor
    auto_open_people:
      name: People to Auto Open For
      description: >
        Specify the people for whom the front door should auto-open when they arrive home.
      selector:
        entity:
          domain: person
          multiple: true
    auto_relock_delay:
      name: Auto Close Delay
      description: >
        Time to wait before auto-locking the front door after it has been detected closed by the sensor, and
        the lock has not been auto-opened.
      default:
        hours: 0
        minutes: 5
        seconds: 0
      selector:
        duration:
    auto_unlock_time_to_enter:
      name: Auto Unlock Time to Enter
      description: >
        Time to keep the door open after an auto-open request before locking it again. This parameter is present so
        the delay can be extended over the auto-close delay if desired.
      default:
        hours: 0
        minutes: 15
        seconds: 0
      selector:
        duration:
    debug_mode:
      name: Debug Mode
      description: If on, the automation will log actions instead of performing them. In addition, the time values will be treated as seconds instead of minutes.
      default: false
      selector:
        boolean:

variables:
  debug_mode: !input debug_mode
  door_open_sensor: !input door_open_sensor
  door_lock: !input door_lock

triggers:
  - trigger: state
    entity_id: !input auto_open_people
    from: "not_home"
    to: "home"
    id: person_just_arrived

  - trigger: state
    entity_id: !input door_lock
    from: "locked"
    to: "unlocked"
    id: lock_unlocked
    for: !input auto_relock_delay
  # - trigger: homeassistant
  #   event: start
  #   id: hass_startup

conditions: []

mode: single

actions:
  - event: automation_log
    event_data:
      level: info
      message: >
        Trigger {{ trigger.id }} fired at {{ now().strftime('%H:%M:%S') }}
        (lock={{ states(door_lock) }}, door={{ states(door_open_sensor) }})

  # automatically unlock the door for arriving person
  - if:
      - condition: template
        value_template: >
          {{ debug_mode | bool }}
    then:
      - event: automation_log
        event_data:
          level: info
          message: >
            [Debug Mode] Would unlock front door {{ door_lock }} for arriving person(s) {{ trigger.entity_id }}.
    else:
      - service: lock.unlock
        target:
          entity_id: !input door_lock
  - wait_for_trigger:
      - alias: Wait for door to be opened, then closed
        trigger: state
        entity_id: !input door_open_sensor
        from: "on"
        to: "off"
        timeout: !input auto_unlock_time_to_enter
  - if:
      - "{{ wait.completed }}"
    then:
      # The wait completed (i.e. door was opened and closed). Set a timer to relock after auto_relock_delay
      - delay: !input auto_relock_delay
      - &LOCK_DOOR_ACTION
        if:
          - condition: state
            entity_id: !input door_open_sensor
            state: "off"  # Still closed?
          - condition: state
            entity_id: !input door_lock   
            state: "unlocked"  # Still unlocked?
        then:
          - if:
              - condition: template
                value_template: >
                  {{ debug_mode | bool }}
            then:
              - event: automation_log
                event_data:
                  level: info
                  message: >
                    [Debug Mode] Would lock front door {{ door_lock }}.
            else:
              - service: lock.lock
                target:
                  entity_id: !input door_lock
    else:
      # The wait did not complete (i.e. timeout). ReLock the door.
      - *LOCK_DOOR_ACTION


