blueprint:
  name: Open Garage on Arrival (with Enable Toggle and Timeout)
  description: >
    Opens the garage when a person arrives home, if they've been away for a set time and the enable boolean is on.
    Also closes the garage when the enable boolean is turned on manually.
  domain: automation
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    enable_boolean:
      name: Enable Input Boolean
      selector:
        entity:
          domain: input_boolean
    garage_cover:
      name: Garage Door
      selector:
        entity:
          domain: cover
    min_away_seconds:
      name: Minimum Time Away (seconds)
      default: 180
      selector:
        number:
          min: 1
          max: 3600
          step: 10
    turn_off_boolean:
      name: Turn off Enable Boolean After Trigger?
      default: true
      selector:
        boolean:
    auto_close_on_enable:
      name: Auto-Close Garage on Enable?
      default: false
      selector:
        boolean:
    test_mode:
      name: Test Mode
      description: If on, the automation will log actions instead of performing them.
      default: false
      selector:
        boolean:

variables:
  min_away_seconds: !input min_away_seconds
  garage_cover: !input garage_cover
  turn_off_boolean: !input turn_off_boolean
  test_mode: !input test_mode
  auto_close_on_enable: !input auto_close_on_enable

triggers:
  - trigger: state
    from: "not_home"
    to: "home"
    entity_id: !input person_entity
    id: arrival

  - trigger: state
    from: "off"
    to: "on"
    entity_id: !input enable_boolean
    id: enable

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: arrival
          - condition: state
            entity_id: !input enable_boolean
            state: "on"
          - condition: template
            value_template: >
              {{ (as_timestamp(trigger.to_state.last_changed) -
                  as_timestamp(trigger.from_state.last_changed)) > (min_away_seconds | int) }}
        sequence:
          - event: automation_log
            event_data:
              level: info
              message: >
                Arrival detected for {{ trigger.entity_id }} after being away for
                {{ (as_timestamp(trigger.to_state.last_changed) -
                    as_timestamp(trigger.from_state.last_changed)) | int }} seconds.
          - if:
              - alias: "In test mode, don't actually open the garage"
                condition: template
                value_template: "{{ not test_mode }}"
            then:
              - service: cover.open_cover
                target:
                  entity_id: "{{ garage_cover }}"
              - delay: "00:00:05"
          - if:
              - alias: "Turn off enable boolean after opening"
                condition: template
                value_template: "{{ turn_off_boolean }}"
            then:
              - service: input_boolean.turn_off
                target:
                  entity_id: !input enable_boolean
      - conditions:
          - condition: trigger
            id: enable
          - condition: template
            value_template: "{{ auto_close_on_enable }}"
        sequence:
          - event: automation_log
            event_data:
              level: info
              message: >
                Enable boolean turned on; auto-closing garage door {{ garage_cover }}.
          - if:
              - alias: "In test mode, don't actually close the garage"
                condition: template
                value_template: "{{ not test_mode }}"
            then:
              - service: cover.close_cover
                target:
                  entity_id: "{{ garage_cover }}"
