blueprint:
  name: Open Garage on Arrival (with Enable Toggle and Timeout)
  description: >
    Opens the garage when a person arrives home, if they've been away for a set time and the enable boolean is on.
    Also closes the garage when the enable boolean is turned on manually.
  domain: automation
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    enable_boolean:
      name: Enable Input Boolean
      selector:
        entity:
          domain: input_boolean
    garage_cover:
      name: Garage Door
      selector:
        entity:
          domain: cover
    min_away_seconds:
      name: Minimum Time Away (seconds)
      default: 180
      selector:
        number:
          min: 0
          max: 3600
          step: 10
    turn_off_boolean:
      name: Turn off Enable Boolean After Trigger?
      default: true
      selector:
        boolean:

trigger:
  - platform: state
    from: 'not_home'
    to: 'home'
    entity_id: !input person_entity
    id: arrival

  - platform: state
    from: 'off'
    to: 'on'
    entity_id: !input enable_boolean
    id: enable

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: arrival
          - condition: state
            entity_id: !input enable_boolean
            state: 'on'
          - condition: template
            value_template: >
              {{ (as_timestamp(trigger.to_state.last_changed) - as_timestamp(trigger.from_state.last_changed)) > (min_away_seconds | int) }}
        sequence:
          - service: cover.open_cover
            target:
              entity_id: !input garage_cover
          - delay: "00:00:05"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ turn_off_boolean }}"
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: !input enable_boolean

      - conditions:
          - condition: trigger
            id: enable
        sequence:
          - service: cover.close_cover
            target:
              entity_id: !input garage_cover

mode: single
